name: Deploy website
on:
# Adding triggers other than PRs will break a lot of the code here 
#   (anything using github.event or github.ref)
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:
    inputs:
      deploy_prod:
        description: "Deploy to prod (requires approval and wait time 120m)"
        default: false
        type: boolean
jobs:
  build-web:
    concurrency:
      group: web-${{ github.ref }}
      cancel-in-progress: true   
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: only allow workflow_dispatch from main
        if: ${{ github.event_name == 'workflow-dispatch' }}
        run: |
          if ${{ github.ref == 'refs/heads/main' }} ; then
            echo "::error title=Bad branch selected::You can only run manual workflows from the main branch"

      - name: Set env variables
        shell: bash
        working-directory: functions
        run: |
          if  ${{ github.ref == 'refs/heads/main' }} ; then
            if ${{ inputs.deploy_prod || false }}; then
              echo "GATSBY_FUNCTIONS_URL=https://europe-central2-centrifuge-production-x.cloudfunctions.net/webapi-main" >> .env
            else
              echo "GATSBY_FUNCTIONS_URL=https://europe-central2-peak-vista-185616.cloudfunctions.net/webapi-main" >> .env
            fi
          else
            echo "GATSBY_FUNCTIONS_URL=https://europe-central2-peak-vista-185616.cloudfunctions.net/webapi-${{ github.head_ref || github.ref_name }}" >> .env
          fi

      - name: Setup Node
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 #@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Archive functions artifacts
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # @v3.1.2
        with:
          name: web-package
          retention-days: 1
          path: public/

  publish-to-gcs:
    concurrency:
      group: web-${{ github.ref }}
      cancel-in-progress: true    
    needs: build-web
    permissions:
      contents: read
      id-token: write 
      pull-requests: write
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy_prod && 'production' || 'development' }}
    steps:
      - name: set preview URL
        shell: bash
        run: | 
          if ${{github.ref == 'refs/heads/main'}}; then
            if ${{ inputs.deploy_prod || false }}; then
              echo "site_url=www.centrifuge.io" >> $GITHUB_ENV
            else
              echo "site_url=website-staging.k-f.dev" >> $GITHUB_ENV
            fi
          else
            echo "site_url=preview${{ github.event.number }}.k-f.dev" >> $GITHUB_ENV
          fi
      - name: download webpack
        id: download
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # @v3.0.2
        with:
          name: web-package
          path: webpack

      - name: Auth gcloud
        id: gauth
        uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d # @v1
        with:
          workload_identity_provider: '${{ secrets.GWIP }}'
          service_account: '${{ secrets.GSA }}'
      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1' 

      - name: try to create bucket
        id: create_bucket
        continue-on-error: true
        run: |
          gsutil mb gs://${{ env.site_url }}
          gsutil iam ch allUsers:objectViewer gs://${{ env.site_url }}
          gsutil web set -m index.html -e 404.html gs://${{ env.site_url }}

      - name: push to bucket
        id: push
        run: gsutil -m rsync -d -c -r ${{steps.download.outputs.download-path}} gs://${{ env.site_url }}

      - name: PR comment with preview URL
        uses: thollander/actions-comment-pull-request@v2
        if: github.event_name == 'pull_request' && steps.push.outcome == 'success'
        with:
          message: |
            Deployed webiste in Google Cloud
            URL: http://${{ env.site_url }}
            Commit #: ${{ github.event.pull_request.head.sha }}   
      - run: echo "::notice title=web_url::${{ env.site_url }}"     

  notify_slack:
    needs: publish-to-gcs
    runs-on: ubuntu-latest
    if: inputs.deploy_prod
    steps:
        - name: Slack on prod publishing
          uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_MESSAGE: "centrifuge.io website deployed"

  check_function_exists:
    permissions:
      contents: read
      id-token: write 
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy_prod && 'production' || 'development' }}
    steps:   
      - name: Auth gcloud
        id: gauth
        uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d # @v1
        with:
          workload_identity_provider: '${{ secrets.GWIP }}'
          service_account: '${{ secrets.GSA }}'
      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1' 

      - name: check function
       # Deploy function for every website PR deployed for previews
        id: check_function
        shell: bash
        run: |
          if gcloud functions describe --region europe-central2 webapi-${{ github.head_ref || github.ref_name }} 2> /dev/null; then
            echo "deploy=false" >> $GITHUB_OUTPUT
          else
            echo "deploy=true" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true    
      - run: echo "deploy == ${{ steps.check_function.outputs.deploy }} \n event == ${{ github.event_name }}"
      - run: |
          if ${{ steps.check_function.outputs.deploy == 'true' }} &&  ${{github.event_name == 'pull_request'}} || ${{github.ref == 'refs/heads/main'}}; then
            echo "Deploy function!"
          fi
    outputs:
      deploy_function: ${{ steps.check_function.outputs.deploy }} 

  
  func_deploy:
    needs: check_function_exists
    if: ${{needs.check_function_exists.outputs.deploy_function == 'true' &&  github.event_name == 'pull_request' || github.ref == 'refs/heads/main'}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy == ${{ needs.check_function_exists.outputs.deploy }} \n event == ${{ github.event_name }}"
      - run: |
          if ${{ needs.check_function_exists.outputs.deploy_function == 'true' }} &&  ${{github.event_name == 'pull_request'}} || ${{github.ref == 'refs/heads/main'}}; then
            echo "Deploy function!"
            echo "${{github.ref}}"
          fi
      
    # if: ${{needs.check_function_exists.outputs.deploy_function == 'true' &&  github.event_name == 'pull_request' ||  ${{github.ref == 'refs/heads/main'}}
    # uses: ./.github/workflows/functions-deploy.yml
    # secrets: inherit
    # with:
    #   deploy_prod: ${{ inputs.deploy_prod }}

